import { Providers } from '@/components/Providers'
import { Inter } from 'next/font/google'
import { Container, Button, Flex, Heading, Spacer } from '@chakra-ui/react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<Container maxWidth={1200} as='main'>
						<Flex my={10} minWidth='max-content' alignItems='center' gap='2'>
							<Heading size='md' as={Link} href='/'>
								Nextfire
							</Heading>
							<Spacer />
							<Button colorScheme='teal' as={Link} href='/create-post'>
								Create post
							</Button>
						</Flex>
						{children}
					</Container>
				</Providers>
			</body>
		</html>
	)
}
